version: "3.10"

services:
  proxy:
    container_name: proxy
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 8000
        published: 5000
        mode: host
    volumes:
      - ./back:/back

  proxy_nginx:
    image: nginx:1.23-alpine
    container_name: proxy_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 80
        published: 4000
        mode: host
    volumes:
      - ./back/project/static:/static
    depends_on:
      - proxy
    links:
      - proxy

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 80
        published: 80
        mode: host
    volumes:
      - ./front:/front
    depends_on:
      - proxy_nginx
    links:
      - proxy_nginx